<footer class="site-footer">
    <div class="container footer-grid">

    <div>
        <h2>Contact</h2>
        <p>
            Email:
            <a href="mailto:info@G07HealthDep.com">
                info@G07HealthDep.com
            </a>
        </p>
    </div>

    <div>
        <h2>Project Links</h2>

        <p>
            <a href="https://chanmyaeoo.atlassian.net/jira/software/projects/GHRW/summary?atlOrigin=eyJpIjoiMjRjMmI4YTZhYjc0NGNiNmJlZmMxMjY5ZmQ1MmZiNDAiLCJwIjoiaiJ9" target="_blank">
                Jira Project
            </a>
        </p>

        <p>
            <a href="https://github.com/minmyat1010/Assingment-Part-2.git" target="_blank">
                GitHub Repository
            </a>
        </p>
    </div>

    <div>
        <h2>G07 Health Department</h2>
        <p>
            Providing quality healthcare services and supporting community wellbeing.
        </p>
    </div>

</div>

</footer>

</body>
</html>
